//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IlogicNomina2016
{
    using System;
    using System.Collections.Generic;
    
    public partial class cargo
    {
        public int idcargo { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string conceptos { get; set; }
        public Nullable<int> Iddepartamentos { get; set; }
    }
}
